version: 2.1
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - checkout

      - restore_cache:
        name: Restore node_modules
        key:
          - node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
        name: Install
        command: yarn install --frozen-lockfile

      - save_cache:
        name: Save node_modules
        key: node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths:
          - node_modules

      - run:
        name: Lint
        command: yarn lint

      - run:
        name: Test
        command: yarn test

      - run:
        name: Build
        command: yarn build